### ISSUE TITLE
consuming bottled jelly or nut butter bottle does not return glass bottle

### ISSUE THREAD

**Issue by esotericist** [brnbrd/Delightful#1]
other bottled things from the farmer's delight family return the bottle on consumption, so my character apparently eating glass was quite a surprise.

forge 40.1.54, farmer's delight 1.18.2-1.1.2, delightful 1.5.2

**Comment by brnbrd** [comment]
Will fix this in the next version :)

**Comment by esotericist** [comment]
prompt service. i'm definitely getting more than i paid for. :)

**Comment by brnbrd** [comment]
Haha
Fixed as of v1.6

**Comment by esotericist** [comment]
awesome, thanks for the prompt fix. and if i find a new bug i see i can now follow a template. :)
