### ISSUE TITLE
[Forge 1.20.1] Incompatibility with other mods / forge:fruits tags empty error.

### ISSUE THREAD

**Issue by NovaLynxie** [brnbrd/Delightful#100]
**Describe the bug**: A clear and concise description of what the bug is.
Hi there!

I have noticed a strange bug which causes the recipe for Farmer's Delight fruit salad item to become uncraftable when both Delightful and Vintage Delight is introduced into the modpack simultaneously.

But as soon as Delightful is introduced, which changes one of the items in this recipe the `forge:fruits` tag becomes empty and fails to work correctly. I thought I would also bring it to your attention since both Delightful and Vintage Delights are introduced into the same modpack.

I am unsure when this problem occurred, but it seems to be happening with any combination of either mods mentioned in 1.20.1.
Please can this be looked into?

**To Reproduce**: Steps to reproduce the behaviour
1. Install Farmer's Delight, Delightful and Vintage Delight with Forge for 1.20.1.
(optional - include JEI, etc. for recipe checking)
2. Create a world and gather the items required to craft a Fruit Salad.
3. Try to craft the item or view the recipe in JEI.

**Expected behaviour**: A clear and concise description of what you expected to happen.
You should be able to put the items into the crafting table in any orientation as its shapeless and obtain the fruit salad.

**Screenshots**: If applicable, add screenshots to help explain your problem.
Somehow, it ends up like this:
![image](https://github.com/user-attachments/assets/a246ecf6-5849-4c4b-9587-3fd3c0e30b59)

With just Farmer's Delight and Vintage Delight, this recipe works fine and looks like this:
![image](https://github.com/user-attachments/assets/8b85cc07-b9fb-4016-ada1-7e8a66c9c5bf)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Forge 47.3.0 for Minecraft 1.20.1
Farmer's Delight 1.2.4
Delightful 0.1.6

**Additional Notes**:
I have created an identical issue in Vintage Delight since this also affects this mod as well. See here: https://github.com/ribs498/VintageDelight-master/issues/15

**Comment by brnbrd** [comment]
This issue is not caused by Delightful, but Vintage Delight. They modify the fruits tag with a reference to "forge:fruits/gearo_berry" which is not present in latest jar file uploaded to CurseForge. It is however fixed already in their GitHub repository, those changes just need to be reflected in the jar. Unfortunately I can do nothing to fix this, and hopefully @ribs498 can upload the fixed file from GitHub soon.

**Comment by NovaLynxie** [comment]
I see, had suspected it was something to do with Vintage Delight when it was the only mod that broke the recipes when all other mods are fine. Thank you for trying, will wait for them to update their CF page with the patch fix.
