### ISSUE TITLE
[Forge 1.20.1] Recipe conflict with Ars Delight

### ISSUE THREAD

**Issue by lcy0x1** [brnbrd/Delightful#101]
Delightful adds recipes that cut arch log / wood into stripped log / wood and bark, however, Ars Delight adds arch barks that are obtianed by cutting logs as well. Could you make those bark recipes to not load while Ars Delight is present? With recipe conditions.

CurseForge of Ars Delight: https://www.curseforge.com/minecraft/mc-mods/ars-nouveaus-flavors-delight
GitHub of Ars Delight: https://github.com/Minecraft-LightLand/Ars-Nouveau-Flavors-Delight

**Comment by brnbrd** [comment]
Fixed in v3.6.1
