### ISSUE TITLE
Multiple different Electrum Knives if Oreganized is installed

### ISSUE THREAD

**Issue by Qwerty97475** [brnbrd/Delightful#102]
**Describe the bug**: Delightful adds an Electrum Knife to the game if an Electrum Ingot exists, except if Oreganized is installed (which adds an Electrum Ingot) it also adds an Electrum Knife (In a closer colour palette to their Electrum Ingot, mind you).

**To Reproduce**: Install Delightful, Oreganized, and both mods' dependencies.

**Expected behavior**: I expect Delightful to disable their own Electrum Knife to favour Oreganized's, to remove duplicate items and overlapping recipes

**Screenshots**: 
![image](https://github.com/user-attachments/assets/f117d7dc-bec3-4bd2-a334-fae65d742c77)

**Versions**: 
Delightful - 1.20.1-3.6.1
Farmer's Delight - 1.20.1-1.2.5
Forge - 47.3.0

**Comment by Qwerty97475** [comment]
This is NOT an issue with Lead, as Oreganized doesn't add a Lead Knife.

**Comment by brnbrd** [comment]
I have added oreganized as an incompatibility for the Electrum Knife, however this isn't really a bug. My Electrum Knife can be easily disabled in the config.
