### ISSUE TITLE
[Mod Compatibility]the green tea leaves with Dynamic Trees

### ISSUE THREAD

**Issue by BotVodka** [brnbrd/Delightful#103]
I've noticed that the green tea leaves will take place the tree seed dropped when chopping the trees
It's annoying with Dynamic Trees installed since there is really limited tree seeds dropped in that mod
resulting in even no seeds obtained but all tea leaves
though disabling the tea leaves could prevent this
but I guess there are better options like dropping them independently?

**Comment by brnbrd** [comment]
The Green Tea Leaves do not take the place of the dropped item. They are dropped in addition to existing generated loot using a loot modifier.
