### ISSUE TITLE
Animal Fat & Oil Not Disabled via Config

### ISSUE THREAD

**Issue by katubug** [brnbrd/Delightful#11]
**Describe the bug**: In the delightful-common.toml, I have Animal Fat and Animal Oil Bottles disabled. However, they still show up in JEI.

**To Reproduce**: Load up mod, set those two values in the config to "false" - then boot up the game and search JEI for them

**Expected behavior**: I expected the mod to unregister the item and its recipes.

**Screenshots**: If applicable, add screenshots to help explain your problem.

**Versions**: For 1.18.2 - Delightful 2.6, Farmer's Delight 1.2.0, Forge 40.1.80

**Comment by brnbrd** [comment]
Sorry, currently only knives (and possibly a couple select items) dynamically assign their Creative Tab (where JEI pulls from) based on config value. I am working on porting this to all of my configurable items in the future, and have it control the JEI item description as well. Hope to solve this soon (however I will say, 1.18.2 is NOT my priority currently).

**Comment by brnbrd** [comment]
Fixed in v3.1.4
