### ISSUE TITLE
Delight 1.19.2 Game Breaking Update

### ISSUE THREAD

**Issue by Zelioth** [brnbrd/Delightful#13]
Hello, Creator and Dev of Mod pack Friends United. I am currently working on an update and I am testing the Delightful version 3.1.2. After updating to this version it appears to have a major game breaking bug that not only lags a server out almost instantly. but also refuses to allow players to create single player worlds or even log into a server with identical mod installs. I'll place logs and crash reports but I have tested multiple possibilities and the only fix for the issue was downgrading Delightful to 3.1.1

https://bytebin.lucko.me/udzbkrXjT3
https://bytebin.lucko.me/x4E9qyRWiA

[crash-2022-10-27_09.32.39-server.txt](https://github.com/brdle/Delightful/files/9880047/crash-2022-10-27_09.32.39-server.txt)
[crash-2022-10-27_09.33.44-server.txt](https://github.com/brdle/Delightful/files/9880048/crash-2022-10-27_09.33.44-server.txt)

**Comment by brnbrd** [comment]
I'm struggling to find any issues regarding my mod in these logs. And I can not reproduce.

**Comment by LastWordSword** [comment]
Near the bottom of the first crash report:
"Suspected Mods: Corail Tombstone (tombstone), Minecraft (minecraft), Forge (forge)"
So check on the Tombstone mod?

**Comment by Corail31** [comment]
@Zelioth updates your mod 'Earth Mobs'.
https://github.com/Corail31/tombstone_lite/issues/112
Mods using mixin can make nested errors.
