### ISSUE TITLE
Disabling Features cause Invalid Datapack

### ISSUE THREAD

**Issue by Freshah** [brnbrd/Delightful#14]
I disabled most knives and features I wouldnt be using, and on world creation I'd get the "Data pack validation failed" message.
[2022-11-10-1.log.gz](https://github.com/brdle/Delightful/files/9986265/2022-11-10-1.log.gz)

**Comment by brnbrd** [comment]
Likely you set the **chance_wild_salmonberries**, **chance_mini_melon** and **chance_cantaloupe** to _0_, when the range is listed as _>0_.
![image](https://user-images.githubusercontent.com/18539948/201494809-68e2bffa-4bfc-459c-b904-ec3199a2bb5a.png)
However, I will make a change to my config system to prevent this in the future.

**Comment by brnbrd** [comment]
Done
