### ISSUE TITLE
Crash with latest Farmer's Respite

### ISSUE THREAD

**Issue by PhoenixKnight3** [brnbrd/Delightful#15]
Seems that something changed in FR's registry causing Delightful's tea items to break

Delightful 3.1.2-1.19+
Farmer's Respite 1.19-2.0

[crash-2022-11-11_23.09.12-server.txt](https://github.com/brdle/Delightful/files/9994019/crash-2022-11-11_23.09.12-server.txt)

**Comment by brnbrd** [comment]
Fixed in v3.1.3
