### ISSUE TITLE
Cooked Venison Chops chopping duplication

### ISSUE THREAD

**Issue by Nachtflame** [brnbrd/Delightful#16]
**Describe the bug**: Cooked Venison Chops duplicate via Chopping.

**To Reproduce**: Acquire Cooked Venison Chops, and chop them on the cutting board, repeat as desired

**Expected behavior**: Cooked Venison Chops cutting board recipe to use `"item": {delightful:cooked_venison}`, not `"tag": {delightful:cooked_venison}`

**Screenshots**: https://cdn.discordapp.com/attachments/999310127645589565/1043627687312375908/2022-11-19_12.41.08.png

**Versions**: 
Delightful-1.19-3.1.3
FarmersDelight-1.19-1.2.0
Forge-43.1.43

**Comment by brnbrd** [comment]
Fixed in v3.1.4
Will have a better solution soon
