### ISSUE TITLE
[Feature Request] Disabled knifes shouldn't appear on jei

### ISSUE THREAD

**Issue by IlTAKlI** [brnbrd/Delightful#17]
When looking though cutting board recipes it cycles through all knifes even if they're disabled, I feel like they shouldn't appear as it makes it confusing to people which knifes they can obtain if/when the mod is included in a modpack

**Comment by brnbrd** [comment]
I have partially fixed this in v3.1.4 (removed disabled items from Creative and JEI).
As it stands, there was a bug in JEI not removing these items from tags. I have talked with Mezz and he fixed the bug, the file should release soon (just waiting on one more small hiccup).

Please give v3.1.4 a shot with the new [JEI](https://www.curseforge.com/minecraft/mc-mods/jei/files) version when it is out.
