### ISSUE TITLE
Rotten Leather Food Item

### ISSUE THREAD

**Issue by NamelessGamer06** [brnbrd/Delightful#2]
I think there should be a version of the Chunkwich which uses the jerky instead of sweeten chunk as to get rid of the hunger effect

**Comment by kade7263** [comment]
Good idea.

**Comment by brnbrd** [comment]
Been thinking about this, I am now trying to be more cautious in adding food items that are less distinct from one another (even having regrets with the Deluxe Cheeseburger, lol), so let me ask you: should the current Chunkwich simply not have any hunger effect at all, and still be crafted with the Sweetened Chunk? What it does currently have is already a relatively small effect. Let me know your thoughts!
