### ISSUE TITLE
[Suggestion] [1.18.2] Honey Glazed Walnut Usage

### ISSUE THREAD

**Issue by LilJagty** [brnbrd/Delightful#20]
Hi there! Your mod is a nice compat layer for FD and Ecologics- thanks for the work you've put into it!

Not sure if it's been changed for 1.19, but in 1.18.2, the food values of the Honey Glazed Walnut are barely an improvement on the Ecologics Walnuts all by themselves. As honey can be annoying to get, I'd love to see a slight buff to the saturation of the Honey Glazed Walnut. I know it's a small detail, but I'd appreciate it.

Thanks!
-LilJagty

**Comment by brnbrd** [comment]
Done in 1.19.2, however 1.18.2 isn't in active development. If you want, you could PR the change for 1.18.2 and I will merge it. You can then retrieve the build from the workflow artifacts.

Edit: nevermind, I will publish a new 1.18.2 version with backported features.

**Comment by brnbrd** [comment]
Done in 3.2.1
