### ISSUE TITLE
[1.18.2] Recipe error

### ISSUE THREAD

**Issue by The-Goat-HUN** [brnbrd/Delightful#26]
**Describe the bug**: Crafting ice cream with Matcha has Salmonberry Ice Cream as output.

**To Reproduce**: Use Matcha to craft the Salmonberry Ice Cream

**Screenshots**: ![image](https://user-images.githubusercontent.com/46354254/217899369-a624f08d-daaa-4b0f-a80e-3dafd9f7ac1b.png)

**Versions**: Delightful-1.18.2-3.2.1, FarmersDelight-1.18.2-1.2.0

**Comment by brnbrd** [comment]
Sorry, I see this error occurs in the recipes for when Neapolitan isn't installed. Will fix

**Comment by brnbrd** [comment]
Fixed in 1.19.2. 1.18 isn't being actively worked on, but this will be fixed if it does see an update
