### ISSUE TITLE
Pumpkin Pie can't be cutted

### ISSUE THREAD

**Issue by ElMolgajete** [brnbrd/Delightful#27]
**Describe the bug**: When you try to place the pumpkin pie on a cutting board it places the block above the cutting board instead of placing the item on the cutting board.

**To Reproduce**: Just try to put the pumpkin pie on the cutting board

**Expected behavior**: Place the item in the cutting board to get slices

**Screenshots**:
![2023-02-09_21 37 00](https://user-images.githubusercontent.com/122349451/217994773-efe3f284-bbd3-4bbc-9f93-75c036e0e05b.png)

**Versions**: Delightful 1.19.2-3.2.2, Farmer's Delight 1.19-1.2.0, and Forge 43.2.4.

**Comment by brnbrd** [comment]
Fixed in v3.2.3
