### ISSUE TITLE
[1.18.2] Lavender Tea isn't removed from Cooking Pot recipe lists when Farmer's Respite is installed

### ISSUE THREAD

**Issue by CyrusJazzberry** [brnbrd/Delightful#28]
**Describe the bug**: Lavender Tea isn't removed from Cooking Pot recipes when Farmer's Respite is active - this also applies to Miner's Delight's Copper Pot. Lavender Tea can still be brewed via a Kettle, but doesn't consume any water in the process.

**To Reproduce**: Make a new world with Farmer's Delight and the addons listed below, and check Lavender Tea's recipes with JEI.

**Expected behavior**: Lavender Tea to only be made via a Kettle.

**Screenshots**: No screenshots needed.

**Versions**: Minecraft 1.18.2, Farmer's Delight 1.2.0, Delightful 2.6, Forge 40.2.1. Additionally running Farmer's Respite 1.3.0 and Miner's Delight 1.0.3.

**Comment by brnbrd** [comment]
Why are you using Delightful 2.6? I could not replicate this in any newer versions of the mod
