### ISSUE TITLE
Add A Config

### ISSUE THREAD

**Issue by kade7263** [brnbrd/Delightful#3]
I don't know if it already exists in the mod, but it would be nice if there was a way to disable the different knife variants and only have the new cabinets and foods.

**Comment by kade7263** [comment]
It would be nice to disable specific types of knives and leave some open, like the copper knife, (by the way, will the copper knife oxidize?)

**Comment by brnbrd** [comment]
Yes, the mod has a configuration since version 1.7. You can find it at config/delightful-common.toml or edit in game with a mod like Configured. Everything can be disabled, so feel free to pick and choose which knives to use! Oxidation for copper items may be in the works :)
