### ISSUE TITLE
[1.19.2] can't use knife

### ISSUE THREAD

**Issue by MistereMoth** [brnbrd/Delightful#31]
I saw a reddit post about this issue too, it said that it was due to this or some other mod that gives compatibility to farmer's delight to other mods

but anyway the mod makes it so knifes aren't detected as knifes so they can't be used to cut stuff or do anything else knifes do, and please fix this as soon as possible

![image](https://user-images.githubusercontent.com/125777173/227072488-58036b53-5cce-49f3-898d-9d3a949904b4.png)
![image](https://user-images.githubusercontent.com/125777173/227072524-0a8f84d3-b369-4b4d-a9d3-31a594629d2b.png)

i'm using the latest versions of forge and all the mods available for this minecraft version

forgot to mention that it gets fixed when i add aquaculture 2 but i don't wanna use that mod because it has bad compatibility and i also think it stinks so please fix it

**Comment by MistereMoth** [comment]
please just fix this already i have the feeling it existed for longer and i want to continue playing on my modpack

**Comment by brnbrd** [comment]
This issue is not caused by my mod. It is likely that you are using [Farmer's Compats](https://www.curseforge.com/minecraft/mc-mods/farmers-compats) which I have heard causes the issue in reality. Please refrain from spamming in the future.

**Comment by MistereMoth** [comment]
oh i'm so sorry for the trouble
