### ISSUE TITLE
[Suggestion] Allow for Garden Cloche usage like Farmer's delight

### ISSUE THREAD

**Issue by ffuentesm** [brnbrd/Delightful#32]
Hello, just suggesting allowing the seeds to be able to grow inside the garden cloches, like how the ones in FD do. 
![image](https://user-images.githubusercontent.com/44974827/227405740-f91c170d-ff88-413c-b02f-154337f2de9f.png) 
![image](https://user-images.githubusercontent.com/44974827/227405800-8f004fd7-ca68-4c23-bb87-8d9c19165c97.png) 
![image](https://user-images.githubusercontent.com/44974827/227405820-31211bf1-8af4-4789-8f82-5263bccf5956.png)

So this would just let the plants this mod like the salmonberry to grow inside the cloches.

**Comment by brnbrd** [comment]
Done in v 3.2.3
