### ISSUE TITLE
[Feature Request] Make the override tag 'forge:cheese_or_milk' disableable.

### ISSUE THREAD

**Issue by Neposis** [brnbrd/Delightful#35]
Good afternoon,
I am currently working on a modpack and found that I couldn't override the forge tag forge:cheese_or_milk that is added as part of this mod using datapacks. I have other mods that have cheese so wanted to use them strictly and have done that using the forge:cheese tag, however the only solution I found was to manually change it within the mod file which doesn't really sit well with how curseforge works.

Making it part of the config would be grand if possible.

Kind regards,
David

**Comment by brnbrd** [comment]
Hello. I was thinking of actually changing up that tag, and removing it all together. I want to use "forge:cheese" tag in the recipes in the case that it isn't empty, and "forge:milk" in the other case. I will probably add an opt-out of the cheese tag as well if they want to force a milk recipe. Will be done very soon.
