### ISSUE TITLE
[1.19.2] [FORGE] Salmonberry no natural growth

### ISSUE THREAD

**Issue by ffuentesm** [brnbrd/Delightful#39]
**Describe the bug**: I am planting Salmonberry and they do not naturally grow into berries, I need to bonemeal them to get the berries

**To Reproduce**: Plant on farmland with water and a Salmonberry bush and wait.

**Expected behavior**: The bush would grow and provide Salmonberry when fully grown. 

**Screenshots**:
![image](https://user-images.githubusercontent.com/44974827/235415489-29781afe-8c6c-4977-b251-73cd2cf5ae93.png)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Forge:43.2.8
Delightful:3.2.4
Farmer's Delight:1.19.1.2.0

**Comment by brnbrd** [comment]
It currently requires rain to grow, but this is changing a bit in the next update
