### ISSUE TITLE
error during the common_setup event 

### ISSUE THREAD

**Issue by racc957** [brnbrd/Delightful#4]
i mentioned this issue on the forge page and i was told to post the logs. 
i seem to get a common_setup event error.
here is the screen it displays and the log 

![Ekran görüntüsü 2022-08-02 112444](https://user-images.githubusercontent.com/110455416/182328566-8738ea6f-a52f-4e58-898f-b2a06c72b63c.png)
[crash-2022-08-02_11.16.08-fml.txt](https://github.com/brdle/Delightful/files/9240384/crash-2022-08-02_11.16.08-fml.txt)
[latest.log](https://github.com/brdle/Delightful/files/9240385/latest.log)

**Comment by brnbrd** [comment]
Do you happen to be using a language other than English? Looks like I forgot a Locale in my string conversion code, causing "tin" to not accurately uppercase to "TIN". I'll get this fixed in a few.

**Comment by racc957** [comment]
yes i do use a language other than english i think this clears things up thank you for your time :•)

**Comment by brnbrd** [comment]
Fixed in v1.11 (I think)
