### ISSUE TITLE
[Feature Request] Create Stuff & Additions Blazing knife

### ISSUE THREAD

**Issue by saltyseadoggo** [brnbrd/Delightful#41]
**Describe the bug**: Delightful does not add a knife for the Blazing toolset from Create Stuff & Additions.

**To Reproduce**:
- Load this mod alongside Create Stuff & Additions
- Search up `Blazing` in the creative mode search bar

**Expected behavior**:
There would be a Blazing Knife added by Delightful

**Versions**:
Forge 43.2.8
Create Stuff & Additions 2.0.2a
Farmer's Delight 1.2.0
Delightful 3.2.4

**Comment by brnbrd** [comment]
Added in v3.3
