### ISSUE TITLE
Create's builder's tea recipe gets disabled if Delightful is installed.

### ISSUE THREAD

**Issue by BoelGaymer** [brnbrd/Delightful#48]
**Describe the bug**: You can't make Builder's tea with Delightful installed.

**To Reproduce**: Load Create and Delightful together.

**Expected behavior**: Be able to mix builder's tea.

**Screenshots**: n/a

**Versions**: Delightful 3.3, Farmer's Delight 1.2.1, and Forge versions 43.2.3, create 0.5.1b on minecraft 1.19.2.

**Comment by brnbrd** [comment]
Sorry about that. The recipe is replaced with compat for tea leaves, and I didn't add in a backup recipe in the case that:
- Green Tea Leaf is disabled in config AND
- Farmer's Respite is not installed
You can temporarily solve this issue by enabling Green Tea Leaf in the config (or installing Farmer's Respite if you like that mod).  If you do either of these things, then Builder's Tea should be enabled again with a recipe requiring Tea Leaves. I will fix the issue in the meantime by adding a fallback recipe and it will go in the next version.

**Comment by brnbrd** [comment]
Fixed in v3.4
