### ISSUE TITLE
Broken compatibility  with Culturals Delights (bamboo mat removed)

### ISSUE THREAD

**Issue by Lgmrszd** [brnbrd/Delightful#5]
**Describe the bug**:
This mod add compat to Cultural Delights, but it's broken on current version.
Bamboo mat (and related recipe type) got removed.
While not noticeable and without big impact on the gameplay, it still causes KubeJS to print error in the chat.

**To Reproduce**:
- Install Delightful, Cultural Delights and KubeJS
- Load the game
- Check recipes

**Expected behavior**: No error displayed

**Screenshots**:
![image](https://user-images.githubusercontent.com/16291541/186312840-9fdcf263-4eea-4f8e-be13-4164cc1f56a7.png)

KubeJS error:

```
[Render thread/WARN] [KubeJS Server/]: Failed to parse recipe 'culturaldelights:mat_rolling/koi_nigiri[culturaldelights:mat_rolling]'! Falling back to vanilla: java.lang.NullPointerException: Unknown recipe type: culturaldelights:mat_rolling
[Render thread/WARN] [KubeJS Server/]: Failed to parse recipe culturaldelights:mat_rolling/koi_nigiri[culturaldelights:mat_rolling]:
[Render thread/ERROR] [KubeJS Server/]: java.lang.NullPointerException
```

**Versions**:
Farmer's Delight: 1.1.2
Cultural Delights: 0.12.1 (Haven't tested on 0.13 yet)
Delightful: 1.12
Forge: 40.1.73

**Comment by brnbrd** [comment]
Fixed with 1.18.2 v2.0
