### ISSUE TITLE
Cactus Chunk cannot be cooked on campfire

### ISSUE THREAD

**Issue by saltyseadoggo** [brnbrd/Delightful#50]
**Describe the bug**: 
Despite being a food item that can be cooked in the smoker, Cactus Chunk cannot be cooked into cactus steak on a campfire.

**To Reproduce**:
- Right click cactus chunk on lit campfire
- Observe how it does not go onto the campfire to be cooked

**Expected behavior**:
Cactus chunk would be able to be cooked on a campfire.

**Versions**:
Forge 43.2.8
Farmer's Delight 1.2.1
Delightful 3.3

**Comment by brnbrd** [comment]
Fixed in v3.4
