### ISSUE TITLE
Salmonberrys not compatible with Create

### ISSUE THREAD

**Issue by VastayanWings** [brnbrd/Delightful#52]
the salmonberry brushes are not compatible with create, meaning the harvesters dont harvest them, they destroy them without any drops
requesting to make salmonberry bushes please compatible with create harvesters

mc-version: 1.19.2 , forge 43.2.14
delightful version: 3.3
create version:  0.5.1.b

**Comment by drakray** [comment]
still an issue in 1.20.1 https://github.com/Creators-of-Create/Create/issues/4387

**Comment by drakray** [comment]
it is indeed fixed
