### ISSUE TITLE
[Mod Compat] Allow Matcha Lattes to be made with Neapolitan Milk Bottles

### ISSUE THREAD

**Issue by f-raZ0R** [brnbrd/Delightful#57]
I. Honestly don't even know if the farmer's respite kettle lets you use a tag as a container, so you may have to duplicate the recipe and do some shenanigans to make it not look weird. But, currently, Matcha Lattes are only craftable with FD Milk Bottles, which are completely overriden and made uncraftable if Neapolitan is installed. This is, a bit of an issue.

**Comment by f-raZ0R** [comment]
Not really sure whether to tag this as Bug or Feature.

**Comment by brnbrd** [comment]
Added in v3.4, although note this issue will still be present for FD items brewed with Milk Bottles
