### ISSUE TITLE
[1.18.2] Minceraft crashed after ineract with "table cut" item

### ISSUE THREAD

**Issue by Willy1123** [brnbrd/Delightful#58]
**Describe the bug**: A clear and concise description of what the bug is.
The "table cut" makes ppl and sometime server crashed.

**To Reproduce**: Steps to reproduce the behavior
I put a "table cut" to put a quartz block to obtein 4 quartz pieces, after put the "table cut" and righ clicked, mi minecraft crashed, and everyone in X radious of that item, crashed too

**Expected behavior**: A clear and concise description of what you expected to happen.
The quartz block should be convert in 4 quartz pieces

**Screenshots**: If applicable, add screenshots to help explain your problem.
[crash-2023-08-30_15.54.25-client.txt](https://github.com/brnbrd/Delightful/files/12477786/crash-2023-08-30_15.54.25-client.txt)
![image](https://github.com/brnbrd/Delightful/assets/15690643/8c42a297-a603-4a26-977d-d28895d81a8f)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Delightful version: 1.18.2-3.2.1
Forge version: 40.2.10
Minecraft: 1.18.2

**Comment by brnbrd** [comment]
Closing due to unsupported version
