### ISSUE TITLE
Crash with FD version 1.2 - 1.18.2

### ISSUE THREAD

**Issue by PhoenixKnight3** [brnbrd/Delightful#6]
Just what the title says crashes with the latest FD version for 1.18.2
[crash-2022-09-20_23.17.27-fml.txt](https://github.com/brdle/Delightful/files/9612740/crash-2022-09-20_23.17.27-fml.txt)

**Comment by brnbrd** [comment]
Yes, I am aware of the update and have indicated on the Curseforge page that a patch is in the works.

**Comment by brnbrd** [comment]
Fixed in v2.6
