### ISSUE TITLE
[Feature] Balancing Living knife recipe (Roots Classic)

### ISSUE THREAD

**Issue by Hamredahl** [brnbrd/Delightful#61]
The current ritual recipe for Living Knife is a level 2 ritual. Every other living tool ritual are level 0.
Suggestion is to lower the level of Living Knife ritual.

[RootsCompat.java](https://github.com/brnbrd/Delightful/blob/fd87fab97f915e377084218eca53cdb54e222477/src/main/java/net/brnbrd/delightful/compat/RootsCompat.java#L10)

I'm wildly assuming it would be a simple change from 2 to 0 in current code `new RitualCrafting(2, 146, 214, 43)`, feel free to bash me if that is incorrect.

**Comment by brnbrd** [comment]
Hmm, wonder how that snuck in there given I just copied the crafting snippet from the Living Sword. I do think that line change is correct, I'll get that fixed shortly.

**Comment by Hamredahl** [comment]
I'm guessing they themselves did a balancing change afterwards considering that at the point where you have a level 2 ritual setup, living tools are often basically useless if very pretty.

**Comment by brnbrd** [comment]
Added in v3.4.2
