### ISSUE TITLE
Salmonberries cant be harvested by Create's mechanical harvester

### ISSUE THREAD

**Issue by SABITRON** [brnbrd/Delightful#62]
**Describe the bug**: When attempting to harvest salmonberry bushes with a mechanical harvester from create, the bush is reset to a younger state of growth (as is expected), but no berries enter the contraption's inventory

**To Reproduce**: Steps to reproduce; Make a contraption with mechanical harvesters (mine was attached to a mechanical bearing) and place a salmonberry bush in its path. The harvester will remove the berries from the bush, but no berries will be collected

**Expected behavior**: The berries should enter the contraptions inventory, (i do not know what happens if the contraption has no storage attached)

**Comment by brnbrd** [comment]
Duplicate of #52
