### ISSUE TITLE
Issue with create stuff and additions's knife compat

### ISSUE THREAD

**Issue by DariusZeBaguette** [brnbrd/Delightful#65]
**Describe the bug**: I was trying the compat knives from stuff n additions and just noticed something: experience tools have a low chance of dropping experience orbs when mining, and the blazing tools don't loose durability in the nether, but the compat knives of theses two toolsets don't have theses propreties

**To Reproduce**: Take an experience knife and mine a lot of blocks (like wool because it's fast) and take a blazing knife and hit mobs or mine blocks in the nether

**Expected behavior**: The experience knife should summon exp orbs after some blocks mined, and the blazing knife shouldnt loose durability in the nether

**Screenshots**: nah

**Versions**: 1.19.2, Delightful: 3.4.1, Farmer's Delight: 1.2.3, and Forge versions: 43.3.5

oh and btw it would be cool if the experience knife could drop exp when cutting things on the cutting board

**Comment by brnbrd** [comment]
Fixed in v3.5.2
