### ISSUE TITLE
Green Tea Leaves Direwolf20 1.19 1.12.0

### ISSUE THREAD

**Issue by cdcecho** [brnbrd/Delightful#67]
Green tea leaves in this modpack arent available for some reason. They show up in crafting recipes or matcha latte but not in just enough items and when i try to get them from breaking leaves off trees with a knife from the modpack i dont get any. Not sure if i should be putting this bug report here or for the modpack so im just doing both. Thanks.

**Comment by brnbrd** [comment]
Ensure the config has it enabled. That's all the support I can provide. If a bug exists in a minimal environment, I'll investigate.
