### ISSUE TITLE
Crash while looking through emi

### ISSUE THREAD

**Issue by mxnmnm** [brnbrd/Delightful#68]
**Describe the bug**: A clear and concise description of what the bug is.
I was looking at the items in the mod using emi and then I crashed after 

https://gist.github.com/mxnmnm/0495b09ee413058596637c6c2f2dbae8

**To Reproduce**: Steps to reproduce the behavior
Idk how to reproduce it :(

**Expected behavior**: A clear and concise description of what you expected to happen.
no crash

**Versions**: Delightful, Farmer's Delight, and Forge versions.
neoforge 47.1.84
Delightful-1.20.1-3.4.2
FarmersDelight-1.20.1-1.2.3

**Comment by gkr0013** [comment]
Dear,

forge 47.2
Delightful-1.20.1-3.4.2
FarmersDelight-1.20.1-1.2.4

+/- same crash when I open the inventory (Just Enough Items)

**Comment by Terrijoo** [comment]
I'm getting the same error on version Delightful-1.20.1-3.5
I'm using the Prominence Modpack (Forge/Neoforge) and it crashes for me every now and then with the same error.
Crash report: https://gist.github.com/Terrijoo/5a482cd2d924d2e4fe2c2d4e46073ebe

neoforge 47.1.99
Delightful-1.20.1-3.5
FarmersDelight-1.20.1-1.2.3

**Comment by brnbrd** [comment]
Let me know if it persists in v3.5.1

**Comment by Terrijoo** [comment]
So been playing now for quite a while without a single crash.
Seems like it is fixed, at least for me.
Thanks for the great work!
