### ISSUE TITLE
Matcha Latte applies both Haste and Haste II

### ISSUE THREAD

**Issue by IdrisQe** [brnbrd/Delightful#69]
The Matcha Latte, according to its tooltip, gives Haste for 1 minute and Haste II for 1 minute at the same time.
I assume this has something to do with the mod compatability checks and the lack of a "Caffinated" effect in my current modpack, but it's still strange behavior, and it should probably only show one of these effects.

**Screenshots**: If applicable, add screenshots to help explain your problem.
![image](https://github.com/brnbrd/Delightful/assets/40530630/af8554b1-4d1b-4ce2-9f8e-c677f6960c3b)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
3.4.2, 1.2.3, and 47.2.0 respectively

**Comment by brnbrd** [comment]
Has been updated in newer versions
