### ISSUE TITLE
Crash with Farmer's Delight 1.2.0

### ISSUE THREAD

**Issue by WordStormRose** [brnbrd/Delightful#7]
**Describe the bug**: A clear and concise description of what the bug is.
Crash on launch with the newest 1.18 forge update of Farmer's Delight
[crash-2022-09-21_09.02.14-fml.txt](https://github.com/brdle/Delightful/files/9618416/crash-2022-09-21_09.02.14-fml.txt)

**To Reproduce**: Steps to reproduce the behavior
Load both Delightful and FD with update 1.2.0 of FD.
**Screenshots**: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/54124339/191554262-e227c474-8737-4ee1-817e-454b5116fdc1.png)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Forge 40.1.80, Farmer's Delight version 1.2.0, Delightful version 2.0

**Comment by brnbrd** [comment]
You are not using the latest version of Delightful. Please check for an update on Curse before posting an issue. Also, this is a duplicate.
