### ISSUE TITLE
[Feature Request] Ambrosia

### ISSUE THREAD

**Issue by neverdestroyer23** [brnbrd/Delightful#70]
Could be a golden fruit salad.
Ambrosia in Greek mythology is the food of the gods, so it's got to be op.

5 gapples
2 g-carrots
a bowl and glowberries for garnish

**Comment by ffuentesm** [comment]
I feel this is more fitted for an Aether or Ice & Fire item recipe compat

**Comment by brnbrd** [comment]
> I feel this is more fitted for an Aether or Ice & Fire item recipe compat

I will consider this, and yes I agree it should be compat for one of those mods in the case it is added

**Comment by ffuentesm** [comment]
Actually, Aether Delight already adds Ambrosia food.
![image](https://github.com/brnbrd/Delightful/assets/44974827/7039d332-f745-4d12-a278-ffb14f9d75fe)
![image](https://github.com/brnbrd/Delightful/assets/44974827/e4f34073-f91e-4c34-93a3-d4f1ffc6e7dc)
And Ice and Fire already has their "Ámbrosia" but mixing Pixie Dust on a Bowl
![image](https://github.com/brnbrd/Delightful/assets/44974827/73a202b2-e8da-4457-9cbe-b5b6bb3073e9)

**Comment by brnbrd** [comment]
Seems like this food is already explored enough, then.
