### ISSUE TITLE
[1.20.1] Salmonberries incompatible with Ars Nouveau's Whirlisprig harvest

### ISSUE THREAD

**Issue by ffuentesm** [brnbrd/Delightful#72]
**Describe the bug**: When planting Salmonberries, they are nor recognised by the Whilspring harvest farm, which should generate resources based on the plans/logs/crops around it. I placed some salmon berries and they are not recognised by the farm.

Also, when the salmon berries are at 100% harvest, they do not display the [FullGrownCropMarker](https://modrinth.com/mod/full-grown-crop-marker), as it should, I tested with other moded crops, and they all automatically show the marked, even other bush plant and 2 tall plants.

**To Reproduce**: Install Ars Nouveau and FullGrownCropMarker
Make a Whirlspring crop farm
plan salmonberries
Wait for the berries to grow

**Expected behavior**: The berries should be picked by the whilrspring as well as display the crop markers when fully grown

**Screenshots**: If applicable, add screenshots to help explain your problem.
![image](https://github.com/brnbrd/Delightful/assets/44974827/5e504811-5550-4117-90a4-b5e064e74e67)
![image](https://github.com/brnbrd/Delightful/assets/44974827/2e304b1c-5d6e-409e-aea7-66c3de851e98)

**Versions**: 
Delightful, Delightful-1.20.1-3.4.2
Farmer's Delight, FarmersDelight-1.20.1-1.2.4
Forge: 47.1.3
ars_nouveau: ars_nouveau-1.20.1-4.9.0-all
crop-marker: crop-marker-forge-1.20.4-1.2.0

**Comment by brnbrd** [comment]
The FullGrownCropMarker "incompatibility" is not one that I can fix without causing issues. That mod actually does not fully support others. Ars Nouveau's Sourceberry has the same issue. I am investigating the Whirlisprig harvest.
