### ISSUE TITLE
Crash with Aether Redux 2.0

### ISSUE THREAD

**Issue by Junnaturefox** [brnbrd/Delightful#75]
Crash Report
[https://mclo.gs/mkjvuVr](https://mclo.gs/mkjvuVr)

When either side is removed, the game runs normally.

Mod Versions:
Farmers Delight-1.2.4
Delightful-3.5.1
Aether Redux-2.0
Forge-47.2.20

**Comment by brnbrd** [comment]
Fixed in v3.5.2
