### ISSUE TITLE
JEI showing erroring tooltip.

### ISSUE THREAD

**Issue by Seristic** [brnbrd/Delightful#76]
**Describe the bug**: A clear and concise description of what the bug is.
This occurs on Singleplayer (Unsure if it is the same as Multiplayer), when I hover over ANY item in JEI it states there is an error loading tooltips. With that said, the error is coming from Delightful from what I understand with the stacktrace including

**To Reproduce**: Steps to reproduce the behavior
As far as I know just install Delightful with Aether: Redux and JEI then start a save and then hover over the JEI and the error should play out.

**Expected behavior**: A clear and concise description of what you expected to happen.
The mod not completely kill JEI due to one item not being found?

**Screenshots**: If applicable, add screenshots to help explain your problem.
![image](https://github.com/brnbrd/Delightful/assets/47360735/a600a98c-7f2b-4466-99b9-342a28af7412)

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Farmer's Delight: 1.20.1-1.2.4
Delightful: 1.20.1-3.5.1
Aether: Redux: 2.0.1

-- Ingredient --
Details:
	Name: Veridium Knife
	Mod's Name: Delightful
	Registry Name: delightful:veridium_knife
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 veridium_knife
	Unique Id for JEI (for JEI Blacklist): delightful:veridium_knife
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 veridium_knife delightful:veridium_knife nbt:{Damage:0}

-- Stack Trace --

**Comment by Zepalesque** [comment]
hi, creator of the aether redux here
the latest update refactored and changed veridium tools completely, this seems to be happening because it uses the old system, which I renamed some methods for in 2.0

(that and the knife textures should probably be updated as I redesigned the tools, but that’s unrelated)

**Comment by Zepalesque** [comment]
oh hold on it appears it got fixed lol nvm

**Comment by katubug** [comment]
I'm late to the party, but just to link things together: https://github.com/Zepalesque/The-Aether-Redux/issues/70

**Comment by brnbrd** [comment]
Fixed
