### ISSUE TITLE
Feature Request: Update Veridium Knife textures

### ISSUE THREAD

**Issue by Zepalesque** [brnbrd/Delightful#77]
In the Aether: Redux’s 2.0 update, I redesigned Veridium tools completely, so it would likely be a good idea to update the textures for this mod’s Veridium knives as well (at least the infused Veridium one, the uninfused one looks fine)

Here is a texture you can use if you want, made to match the rest of the new tool textures:

![infused_veridium_knife](https://github.com/brnbrd/Delightful/assets/60141811/5c9ac0d3-8232-4380-9425-661deb8dd178)

(Hopefully the fact that I didn’t use an existing issue template is fine, there didn’t seem to be one for feature requests)

**Comment by brnbrd** [comment]
In progress

**Comment by Zepalesque** [comment]
oh, wait, I just noticed a small thing for the texture I missed, here’s a tweaked version:

![infused_veridium_knife](https://github.com/brnbrd/Delightful/assets/60141811/ae2ad246-b5ad-4fae-a98a-6f0a28f6a2e9)

**Comment by brnbrd** [comment]
Updated textures in v3.5.2
