### ISSUE TITLE
[Suggestion] Miner's Delight Copper Cup Milk Compatibility

### ISSUE THREAD

**Issue by ffuentesm** [brnbrd/Delightful#78]
Would be possible to add the Copper Cup as an acceptable "Server on" container? 
They can already be used to craft the Milk recipe, so letting them pick up the milk, just like how buckets can, would be useful. 
![image](https://github.com/brnbrd/Delightful/assets/44974827/328f8844-d864-46c9-9d29-856f30362c2d)
![image](https://github.com/brnbrd/Delightful/assets/44974827/cce27129-9e2a-4412-8a35-7eea069e707c)

**Comment by brnbrd** [comment]
Added in v3.5.3
