### ISSUE TITLE
[LOAD FAILED]: Encountered a error during common_setup

### ISSUE THREAD

**Issue by SrRapero720** [brnbrd/Delightful#8]
**Describe the bug**: Failed to start

**To Reproduce**: Install the mod

**Screenshots**:
![image](https://user-images.githubusercontent.com/29090346/191825672-e0d74a37-93e9-40ce-9fe1-cfcc4127b8aa.png)

**Versions**: 
Delightful: Delightful-1.18.2-2.0.jar
Farmer's Delight: FarmersDelight-1.18.2-1.2.0.jar
Forge versions: 40.1.80

**Logs and crashreport:**
[crash-2022-09-22_13.35.17-fml.txt](https://github.com/brdle/Delightful/files/9628557/crash-2022-09-22_13.35.17-fml.txt)
[latest.log](https://github.com/brdle/Delightful/files/9628559/latest.log)

**Comment by brnbrd** [comment]
You are not using the latest version of Delightful. Please update.

**Comment by SrRapero720** [comment]
![image](https://user-images.githubusercontent.com/29090346/191826882-29367c68-856b-4002-a00e-ed4e425a87e6.png)
No new updates...

**Comment by brnbrd** [comment]
> ![image](https://user-images.githubusercontent.com/29090346/191826882-29367c68-856b-4002-a00e-ed4e425a87e6.png) No new updates...

https://www.curseforge.com/minecraft/mc-mods/delightful/files/3999344
![image](https://user-images.githubusercontent.com/18539948/191827341-2ce8d744-8316-4ef2-ac3b-6697dce8ecb9.png)

It's released as a **beta**, is that why your launcher isn't detecting it?

**Comment by SrRapero720** [comment]
Founded: 
![image](https://user-images.githubusercontent.com/29090346/191827694-b2bbcd8c-a9d3-45a9-9cf0-c82b869e5d96.png)
