### ISSUE TITLE
Living Knife is unobtainable without commands

### ISSUE THREAD

**Issue by SynfulChaot** [brnbrd/Delightful#80]
The Living Knife appears to have several issues preventing it from being able to be obtained in 1.20.1.  Even if it is enabled in the config file it neither shows up in JEI or in the creative tab.  Positing that it _did_ show up, which it doesn't, the recipe is broken due to it requiring a Wooden Knife from Farmer's Delight (`farmersdelight:wooden_knife`), an item that doesn't exist in the mod.  From the [wiki](https://github.com/vectorwing/FarmersDelight/wiki/Knife) itself:
> Knives are tiered tools, much like pickaxes and swords, but they cannot be made out of wood or stone. The weakest knife available is the **Flint Knife**.

As the recipe _does_ show an error in the logs, it seems to have no trouble recognizing that the mod has loaded, which is one of the conditionals on the recipe.  I changed the recipe with a datapack to use the Flint Knife instead and it eliminated the recipe error, though the knife remained unobtainable.

---
### Versions:
**Minecraft** - 1.20.1
**NeoForge** - 47.1.99
**Delightful** - 3.5.2
**Farmer's Delight** - 1.2.4
**Roots Classic** - 1.3.1

**Comment by brnbrd** [comment]
Fixed in v3.5.3
