### ISSUE TITLE
suggestion: source berry crate ars nouveau

### ISSUE THREAD

**Issue by Aceplante** [brnbrd/Delightful#81]
The source berries from ars nouveau have no way to be compacted so you end up with massive amounts of them quickly. If you could add a crate from them that would be amazing

forge 1.18.2

**Comment by brnbrd** [comment]
Ars Nouveau already adds a [Sourceberry Sack](https://github.com/baileyholl/Ars-Nouveau/blob/1.20/src/main/resources/assets/ars_nouveau/textures/block/sourceberry_sack_top.png). Also, I am not actively supporting 1.18.2.

**Comment by Aceplante** [comment]
no it doesnt? or at least on 1.18.2
