### ISSUE TITLE
[Suggestion] Acorn Depth

### ISSUE THREAD

**Issue by Beardtongue** [brnbrd/Delightful#82]
Minecraft is a game largely unencumbered by the burden of "realism," but, as far as I am aware, acorns are unfit for human consumption in their natural state. It follows that one could, for instance, add Hunger to raw acorns or reduce their nutrition, and add the further items of roasted (safe for consumption) and chopped acorns (in preparation for nut butter.) Indigenous peoples even have a history of making acorn flour! This would both add a further use for the numerous knives and offset the (perceived) use of raw acorns as a rather over-convenient and powerful early survival food.
Feel free to use any or all of the above advice, or a tweaked version thereof, but it simply strikes me as a bit off to frolic through the trees, living on nothing but unprocessed, toxic tree nuts!

https://www.webmd.com/diet/are-acorns-safe-to-eat
https://en.wikipedia.org/wiki/Acorn#Use_by_Native_Americans

**Comment by brnbrd** [comment]
I'll look into further expanding on acorns in the next updates. Thanks for these suggestions!
