### ISSUE TITLE
Incompatibility between Aether Redux and Delightful causing the game to crash

### ISSUE THREAD

**Issue by Sycon-Senti** [brnbrd/Delightful#83]
When you hover over either the veridium knife or the Infused Veridium Knife, the game crashes and this message appears in the launcher:

```
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'byte net.zepalesque.redux.item.util.VeridiumItem.getCharge(net.minecraft.world.item.ItemStack)'

```

**To Reproduce**: 
1: Have Aether Redux and Delightful installed.
2: Hover over the item Veridium Knife or Infused Veridium Knife in any menu.
3: Observe the game crashing and showing the above message in the launcher.

**Expected behavior**: 
The tooltips for both listed items be displayed correctly.

**Notes**:
JEI handles this crash error with it's own Error handler, so hovering over these items in there does NOT produce this crash (It does however stop you from seeing any tooltips)
I shall also attach a Crash Report to this:

[crash-2024-05-10_03.44.36-client.txt](https://github.com/brnbrd/Delightful/files/15269854/crash-2024-05-10_03.44.36-client.txt)

**Versions**: 
Delightful 3.4.3
Farmers Delight 1.20.1-1.2.4
Forge 47.2.0

**Comment by brnbrd** [comment]
This is an odd one. First off, I can not reproduce. Are you able to reproduce on a minimal instance? (Only FD, Delightful, Aeroblender, Aether, and Aether Redux installed).

My mod no longer references the _getCharge_ method since multiple versions. Could you try updating to the latest as well (3.4.3)? What version of Aether Redux are you on?

**Comment by Sycon-Senti** [comment]
Seems updating to the latest version of Delightful has fully fixed the issue, thank you for the help! Server I play on will need to update too, hence why I hadn't tried updating before.
