### ISSUE TITLE
Milk recipe consumes bucket

### ISSUE THREAD

**Issue by VileoSufora** [brnbrd/Delightful#9]
**Description**: The cooking pot recipe that takes one water bucket, two walnuts (from Ecologics), and one sugar and requires an empty bucket as an output item to craft one milk bucket does not also return the bucket from the initial water bucket when it consumes the ingredients.

**To reproduce**: Place the relevant ingredients in the pot and and heat to craft the milk. The milk appears in the output but requires another bucket to extract.

**Expected behavior**: When the recipe consumed the other ingredients, the bucket should be left behind, or it should use that bucket as the output item.

**Versions**: Delightful 2.6, Farmer's Delight 1.2, and Forge 40.1.70 on Minecraft 1.18.2.

**Comment by brnbrd** [comment]
Hmm, in testing I see this doesn't happen in 1.19 but definitely does in 1.18. Seems there's some disparity between how FD handles Ingredients with containers between these two versions. I'll look into it more

**Comment by brnbrd** [comment]
If this issue still exists, I do not believe it is fixable on my end
