### ISSUE TITLE
[1.20.1] Client Crash

### ISSUE THREAD

**Issue by MokahTGS** [brnbrd/Delightful#91]
Getting a client crash 

**Versions**: Delightful, Farmer's Delight, and Forge versions.
Forge 47.3.1
Farmers Delight 1.20.1.1.2.4
Delightful 1.20.1.3.5.8
Deep Aether 1.20.1.1.0.4 (if it's related)
https://github.com/RazorDevs/Deep-Aether/issues/191

Crash Log: https://pastebin.com/qaczq0SC

**Comment by brnbrd** [comment]
Closing as duplicate + already fixed
