### ISSUE TITLE
Tea leaves drop from leaves despite being disabled.

### ISSUE THREAD

**Issue by Munchalotl** [brnbrd/Delightful#97]
**Describe the bug**: I am running Delightful in a pack with a bunch of other mods, several of which are the kinds of mods that add their own tea leaves and thus should disable the ones from Delightful. Despite this, the Delightful green tea leaves are still able to drop when leaves are destroyed.

**To Reproduce**: 1) Have Delightful installed alongside mods installed that would disable Delightful's green tea leaves, such as Croptopia. 2) Start chopping down trees/breaking tree leaves. Eventually you'll end up with green tea leaves.

**Expected behavior**: Given that they're disabled, I'd expect them to not be obtainable at all.

**Screenshots**:
![2024-10-17_20 11 39](https://github.com/user-attachments/assets/d6e43100-3c0c-44a0-9635-db648924eba0)
You can see here that I've cut down a large spruce tree and that green tea leaves have dropped. You can also see that they should be disabled in the popup at the top of the screen.

**Versions**:
Delightful: v 3.6
Farmer's Delight: v 1.2.4
Forge: v 47.3.7

**Comment by emihead** [comment]
I've actually noticed a similar issue... The green tea leaves show as disabled, even though I never turned them off, and they do still drop like you said.
The only mod I can see in the code that disables tea leaves automatically is Youkai's Homecoming, which I don't have.

**Comment by brnbrd** [comment]
Should be fixed in v3.6.1. Let me know if you still have this or a similar issue
