### ISSUE TITLE
Cutting board recipe that turns bread into nothing

### ISSUE THREAD

**Issue by H-is-the-best-letter** [brnbrd/Delightful#98]
**Describe the bug**: There is a cutting board recipe that just turns bread into nothing.

**To Reproduce**: Try cutting bread on a cutting board, and you get nothing. You can also see in JEI that it's not a bug, but a recipe that turns bread into nothing.

**Expected behavior**: This shouldn't happen

**Screenshots**: ![Base Profile Screenshot 2024 10 31 - 21 23 35 61](https://github.com/user-attachments/assets/2aed7104-089d-4842-903e-b1bea5c7031d)

**Versions**: Delightful (Forge, but check other versions for safety reasons)

**Comment by H-is-the-best-letter** [comment]
It also didn't go away when I disabled all the recipes using the [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod

**Comment by H-is-the-best-letter** [comment]
Just sifted through the versions and found that it first appears on version 3.5.7 of the mod.

**Comment by AverageAnime** [comment]
https://github.com/brnbrd/Delightful/blob/1.20.1/src/main/resources/data/moredelight/recipes/farmersdelight/cutting/bread_slice.json 
This is the recipe in question. It incorrectly has the load condition to check for the absence of the item some_assembly_required:bread_slice, when it should be checking for the presence of More Delight.

**Comment by brnbrd** [comment]
> https://github.com/brnbrd/Delightful/blob/1.20.1/src/main/resources/data/moredelight/recipes/farmersdelight/cutting/bread_slice.json This is the recipe in question. It incorrectly has the load condition to check for the absence of the item some_assembly_required:bread_slice, when it should be checking for the presence of More Delight.

Fixed and yes this was the correct diagnosis. Missed that when adding compat, sorry!
